#
#  MinetopiaSDB-HTC - Configuratie
#  ------------------------------
#  Dit is de hoofdconfiguratie voor de MinetopiaSDB-HTC plugin.
#  Hier kun je instellen hoe lang logs zichtbaar blijven, hoe vaak ze worden opgeslagen,
#  en hoe vaak oude logs worden gecomprimeerd/gearchiveerd.
#
#  Tijdnotatie:
#    - Gebruik 'h' voor uren (bijv. 24h = 24 uur)
#    - Gebruik 'm' voor minuten (bijv. 5m = 5 minuten)
#    - Gebruik 's' voor seconden (bijv. 30s = 30 seconden)
#
#  Let op: Hoe lager je de save_interval of archive_interval zet, hoe meer schijfbewerking en kans op lag!
#

# Hoe lang logs zichtbaar blijven in het menu (daarna worden ze gearchiveerd)
retention_period: 24h  # Standaard: 24 uur

# Hoe vaak alle logs worden opgeslagen naar disk
save_interval: 5m     # Standaard: elke 5 minuten

# Hoe vaak oude logs worden gecomprimeerd/gearchiveerd
archive_interval: 10m # Standaard: elke 10 minuten

# Discord webhook URL voor logmeldingen
# Laat leeg om niet naar Discord te sturen
webhook_url: ""

# Discord role ID om te taggen bij grote wit geld drops (optioneel)
# Bijvoorbeeld: <@&123456789012345678>
whitelistgeld_role: ""
# Minimaal aantal wit geld items voor een tag
whitelistgeld_minimum: 32

#
#  Voor vragen of hulp: github.com/djorr/MinetopiaSDB-HTC
# 