name: MinetopiaSDB-HTC
main: nl.djorr.MinetopiaSDBHTC.MinetopiaSDBHTC
version: 1.0.0
author: Djorr
description: HTC logging plugin voor MinetopiaSDB
api-version: 1.12
depends:
  - Vault
  - Essentials
  - MinetopiaSDBRel
commands:
  sdbhtc:
    description: Hoofdcommando voor MinetopiaSDB-HTC
    usage: /<command> balhistory <speler>
    aliases: [balhistory, balhis]
    permission: sdb.htc.balhistory
    permission-message: §cJe hebt geen permissie om dit commando te gebruiken.
permissions:
  sdb.htc.balhistory:
    description: Gebruik balhistory commando
    default: op